index.js

This PR addresses the missing `dist` folder bug, mentioned in #23

Fix missing dist directory error

---

.babelrc
.github/workflows/test.yml
lib/parse.js
lib/parse.test.js
package.json
yarn.lock

This PR adds Jest to the project, with an associated Github Action workflow, to perform unit testing on the project. Currently, only `lib/parser.js` has associated tests. Additional tests can come in future PRs.
Fulfill #43 partially

Introduce Jest to the project

---

index.js
lib/transform.js

Resolves https://github.com/lazd/coronadatascraper/issues/33

adding method to calculate active case

---

index.js
tasks/findFeatures.js
tasks/findPopulations.js
tasks/scrapeData.js
tasks/writeData.js

Moves parsing and writing data into its own files. Creates a basic reporting object which is written when processing is completed.
Closes #53

Add basic reporter

---

scrapers.js

Adds 7 new counties to the California data:
- San Bernardino
- San Joaquin
- Merced
- Marin
- Butte
- Kings
- Mendocino

Add 7 new California counties

---

scrapers.js

This adds visitor county information to the rest of the counties

Adding visitor counties

---

scrapers.js

This commit adds in the following counties:
- Calaveras, CA
- Colusa, CA
- Del Norte, CA
- Glenn, CA
Annotations have been made in the Google Sheet where sources lack a table like structure

Added additional CA counties

---

scrapers.js

Resolves https://github.com/lazd/coronadatascraper/issues/80
qgolsteyn saw you picked up the ticket, take a look.

Adding france data

---

scrapers.js

Resolves https://github.com/lazd/coronadatascraper/issues/81
I am making the assumption that the data is from https://opendata.arcgis.com/datasets/48fac2d7de0f43f9af938852e3748845_0.csv 
Also, I am calling them "state" but they might be "regions"

adding spain state data

---

lib/parse.js
scrapers.js

updated OH url, re-added code for MD and removed a dupe of LA that was causing issues.

updated and fixed OH, MD and LA

---

scrapers.js

Follows pattern in README.md for html scraping, happy to adjust, message me.

[minor] AUS Australia from health.gov.au

---

.eslintrc.json
.github/workflows/test.yml
cli.js
index.js
initSSL.js
lib/cliArgs.js
lib/datetime.js
lib/datetime.test.js
lib/fetch.js
lib/fs.js
lib/parse.js
lib/parse.test.js
lib/rules.js
lib/stringify.js
lib/transform.js
lib/transform.test.js
package.json
scrapers.js
site/index.html
tasks/findFeatures.js
tasks/findPopulations.js
tasks/scrapeData.js
tasks/writeData.js
timeseries.js
tools/mapJHUCounties.js
yarn.lock

Please focus CR effort on commit ` [patch] manually applied linting fixes, CR carefully `. The rest are unlikely to break anything.
I've tried to reach a balance between consistency to airbnb style, and things that seem to be part of the original author's style choices. Happy to take your lead on this @lazd, but in any case this PR will go stale super quick so keen to get it in ASAP (and while we only have 3 other PRs open, so we don't force many people to rebase).
Hopefully this will make some of the code more readable, by consistency and cleaning up things like stray unused variables.

[patch] add linting, and remove lint

---

lib/transform.js

XKX is from World Bank usage
Closes #88 
Closes #78

correct 3166 codes for Kosovo and Palestine

---

.github/workflows/scraper_status.yml
package.json
scripts/statusSlackBot.js
yarn.lock

This PR adds a new CI script that runs the project every 5 minutes (for now, to test, will be changed to every 2 hours) and reports back on any potential scrapper errors, missing features, etc.

Perform status checks and send to Slack

---

site/index.html
site/style.css

Updated paddings, typography classes for more whitespace

CSS styling modifications

---

scrapers.js

Added IL, USA Data from http://www.dph.illinois.gov/sites/default/files/COVID19/COVID19CountyResults.json

feat: Add IL, USA to scrapers.js

---

lib/datetime.js
scrapers.js
tasks/scrapeData.js

Let scraper be an object keyed on date

---

.eslintrc.json
index.js
lib/caching.js
lib/fs.js
lib/fs.test.js
tasks/writeData.js

Documents and adds tests for `lib/fs.js`

Add tests for fs.js

---

scrapers.js

Fixes Del Norte County which used new labeling for their table. They also created a consolidated test number meaning we don't have to compute them independently

Fix Del Norte County, CA

---

scrapers.js

They changed the wording a bit. I tried making it more robust by checking on less words and allowing for plurals.

Fixed Mendocino County, CA

---

site/index.html
site/index.js
site/style.css

It looks like this:
It uses a rather dubious algorithm to set the color. I fully expect someone to suggest something better. The color scheme isn't that great either.
But it's a map.
Grey: we have case data, but no population data OR "this location is not granular enough"
White: we have case data, and there are no cases

docs: very super ultra basic choropleth map for the current date

---

site/index.html

The link should be `/issues/new` not `/issue/new`

Fixing link to File an issue

---

scrapers.js

Resolves https://github.com/lazd/coronadatascraper/issues/138
Adding new dataset from https://data-cdphe.opendata.arcgis.com/datasets/colorado-covid-19-positive-cases-and-rates-of-infection-by-county-of-identification/
CSV: https://opendata.arcgis.com/datasets/46c727cc29424b1fb9db67554c7df04e_0.csv

Adding data from new CO dataset

---

scrapers.js

Latest updates to DE, FL and PA removed the 'County' transform

feat: add county to de fl pa

---

index.js
lib/fetch.js
lib/fetch.test.js

This PR updates fetch function docs, and adds some initial tests running against actual URLs to verify that fetching works correctly, both locally and on CI.
Closes #45

feat: update fetch and add tests

---

.github/workflows/deploy.yml
.github/workflows/status.yml
.github/workflows/test.yml
cli.js
package.json
scrapers.js
tasks/findFeatures.js
tasks/scrapeData.js
yarn.lock

Reverts lazd/coronadatascraper#139. It causes scripts to fail.

Revert "Enables project to be run on non-experimental Node.js version via esm; removes SSL workaround for env var"

---

site/index.html

This notebook contains code to allow an analyst to get off the ground quickly with this data, as well as some example plots.

Link to Jupyter quickstart notebook

---

scrapers/USA/CA/santa-barbara-county.js

Drop the other PR. This should be a clean commit to add SB County.

Added scraper for Santa Barbara County, California

---

scrapers/USA/CA/kern-county.js
scrapers/USA/CA/monterey-county.js
scrapers/USA/CA/san-luis-obispo-county.js

Added SLO, Monterey and Kern counties in California.

feat: Slo, Monterey, Kern Counties

---

scrapers/AUS/ACT/index.js

Add Australian Capital Territory data from the state's own website.

patch: add AUS ACT

---

scrapers/USA/CO/index.js

Changed CSV url and adjusted field names as necessary

Fixed Colorado, USA

---

lib/caching.js
lib/fetch.js
lib/fs.js
package.json
scrapers/USA/MA/index.js
yarn.lock

This PR adds a scraper with county data for MA, USA. It parses a PDF document with the help of the `pdfreader` library. Some additional functions were added to `fetch` to make this happen.

feat: add MA, USA

---

scrapers/AUS/QLD/index.js

Annoyingly these are separate pages per day, and then just in a paragraph.

[minor] add AUS QLD

---

scrapers/AUS/VIC/index.js

Also annoyingly a paragraph from another page :|

[minor] add AUS VIC

---

site/index.html

it is probably the best visualization for most peoples needs

Added a clear link to the 2D map on the homepage

---

src/events/crawler/scrapers/USA/FL/index.js

fix: Dade County to the canonical Miami-Dade County

---

src/events/crawler/scrapers/GBR/ENG/index.js
src/events/crawler/scrapers/GBR/SCO/index.js

* Adds new scraper for Scotland counties
* Sets state to England for England counties

feat: Scotland data scraper

---

src/events/crawler/lib/datetime.js
src/events/crawler/lib/fetch.js
src/events/crawler/lib/fs.js
src/events/crawler/lib/geography.js
src/events/crawler/scrapers/USA/TN/index.js

Cleanup 15 lint warns via 2 codemods.

fix: codemod cleanups

---

src/events/crawler/scrapers/DEU/DE-BB/index.js

Numbers were incorrect, sorry!

fix: DE-BB scraper coordinates

---

src/events/crawler/lib/fetch.js
src/events/crawler/scrapers/USA/KS/index.js

This PR handles network errors, which have shown to bring the whole crawler when thrown.

fix: handle network errors

---

src/events/crawler/scrapers/AUS/QLD/index.js

fix: AUS Queensland by stripping NBSPs

---

site/index.html

patch: add @piccolbo visualization website

---

src/events/crawler/scrapers/USA/IL/index.js

Rolls Chicago into Cook County.

Fix Chicago IL

---

docs/getting_started.md
docs/sources.md

This PR builds on #395 
* Docs from @HerbCaudill in https://github.com/lazd/coronadatascraper/pull/345
* Add note on how to run unit tests
Second PR for issue #394

Add testing docs

---

src/events/crawler/scrapers/AUS/ACT/index.js

I have no clue why this works but it seems to. Can anyone enlighten me? It scraped 0 last day.

[patch] fix AUS ACT

---

src/events/crawler/scrapers/AUS/QLD/index.js

AUS QLD have added a table, woohoo! Now they're reporting total confirmed to date instead of just new additions.
TODO

use HHS level data from AUS QLD

---

src/shared/lib/geography/index.js

Fix for issue described here: https://github.com/lazd/coronadatascraper/issues/374

Added throw if addEmptyRegions called without any actual data

---

src/shared/lib/fetch/get.js
src/shared/lib/fetch/index.js

I noticed that WA, USA was flakey. The server or headless seems to fail <10% of the time. So I added retry logic. I couldn't get any failures to happen to prove it out though. So can someone review this code carefully?

Added retry logic for headless fetches

---

src/shared/scrapers/AUS/SA/index.js

[patch] fix AUS SA, they have a table now hooray

---

src/shared/scrapers/AUS/QLD/index.js

We don't have a way to map the HHS regions yet, so lets just simplify to fix the map for now.

[patch] Simplify AUD QLD since HHS areas arent mappable yet

---

tools/generateCrosscheckHTML.js

[patch] fix lint in master

---

src/shared/scrapers/AUS/WA/index.js

WA went from unscrapeable to a nice table. Woohoo!

feat: scrape AUS WA

---

site/index.html

Hey guys 👋 
You have done an absolutely amazing job with this project. 
We have used it to build yet another dashboard : https://coronatab.app/dashboard
We also have a New Tab browser extension and a fully relational REST API
We also plan to localise the entire thing into all languages.
Again, can't praise your guys's work enough.
Cheers

Add CoronaTab.app dashboard site link

---

.github/workflows/test.yml

Add missing `run` command to test.yml

---

src/shared/scrapers/USA/WI/index.js

Fixes #426 
timeseries accurate with new cache (tested from 3/12 - 3/28)

fix: wisconsin cases/deaths after 3/25

---

src/shared/scrapers/AUS/ACT/index.js

Australian Capital Territory, AUS more data and resiliency

---

site/index.html

Thanks for all this data. It's excellent to have it all in one place.
Fixes #408

Add link to casualhacker.net/covid19

---

.gitignore
public/index.html

- Added headers to text sections
- moved social links to left
- added logo without margins

Made a few design changes

---

site/crossCheckReport.js
site/lib/geography.js
site/lib/templates.js
site/map.js
src/events/crawler/scrape-data/run-scraper.js
src/events/processor/find-features/index.js
src/shared/lib/geography/index.js
src/shared/scrapers/CAN/index.js
src/shared/scrapers/USA/NYT.js

Found using LGTM https://lgtm.com/projects/g/lazd/coronadatascraper/alerts/?mode=list
*Please review per commit*
There are still a few in find-features
but that function is pretty unwieldy so feel like we might want to simplify before removing those.

Fix some lint

---

src/shared/scrapers/PRI/index.js
src/shared/scrapers/PRI/tests/expected.json
src/shared/scrapers/PRI/tests/salud_gov_pr_pages_coronavirus.aspx

I initially tried to add PR under USA like GU was; however, the feature could not be found for PR, USA. I added it as a country instead.

Added Puerto Rico.

---

src/shared/scrapers/DEU/DE-BB/index.js

DE-BB: fix coords and population (#514)

---

src/shared/scrapers/USA/MN/index.js

Fix broken master lint run

---

src/events/processor/write-data/index.js
src/shared/lib/fs.js
src/shared/timeseries/index.js

1. Pass "space" option to JSON.stringify in fs.writeJSON
2. Generate features.json with space: 0
Makes the file size from 75 MB to 25 MB.

space option in writeJSON

---

src/shared/scrapers/USA/AK/tests/expected.2020-03-27.json

@lazd the tests are updated for AK. Does it look OK for you? 
I don't understand why did the original test have a very buggy looking line `{ "cases": 42 }` in there, but now it looks much better.

update test for AK

---

src/shared/scrapers/USA/UT/index.js

added Southeast, Southwest, and Central Health Districts.

fix: Utah, USA now fleshed out

---

src/shared/scrapers/USA/CA/shasta-county.js

Shasta County fixed

---

src/events/processor/transform-ids/index.js

It was overwriting the wrong key.

fix report findPopulation

---

.github/ISSUE_TEMPLATE/data_issue.md
.github/ISSUE_TEMPLATE/new-scraper.md
.github/ISSUE_TEMPLATE/report-bug.md
.github/ISSUE_TEMPLATE/request-feature.md
.github/ISSUE_TEMPLATE/tech-debt.md
.github/PULL_REQUEST_TEMPLATE.md

Template fixes only, no code changes.
Stole ideas from @lazd 's templates.

Fixed github templates per feedback

---

src/events/processor/find-features/index.js
src/events/processor/find-populations/index.js
src/shared/scrapers/AU/index.js

give AUS govt some slack in their summing

---

README.md
docs/data_fields.md

This is intended as a user-facing document, not a developer one.

separate documentation for data fields

---

.eslintrc.json
docs/sources.md
package.json
site/crossCheckReport.js
site/sources.js
src/events/processor/dedupe-locations/index.js
src/events/processor/find-features/index.js
src/shared/lib/geography/country-levels.js
src/shared/lib/geography/index.js
src/shared/lib/transform.js
src/shared/scrapers/US/CA/santa-barbara-county.js
src/shared/scrapers/US/CO/index.js
src/shared/scrapers/US/HI/index.js
src/shared/scrapers/US/KS/index.js
src/shared/scrapers/US/MO/index.js
src/shared/scrapers/US/ND/index.js
src/shared/scrapers/US/NE/index.js
src/shared/scrapers/US/OH/index.js
src/shared/scrapers/US/RI/index.js
src/shared/scrapers/US/TN/index.js
src/shared/scrapers/US/UT/index.js
src/shared/scrapers/US/WV/index.js
src/shared/timeseries/index.js
tools/mapJHUCounties.js
yarn.lock

Add eslint unicorn plugin (going to use for filename lowercase enforcement soon) and add the first rule, and run --fix on our files.

add eslint unicorn and first rule to use includes

---

src/shared/scrapers/US/MA/index.js

They split Dukes and Nantucket and removed the "EditDate" field

Fixed MA scraper

---

src/shared/scrapers/US/DC/index.js

First, goes to a website to retrieve the cookie necessary to be authorized for the CSV exporter form.
Then, grabs a value from that form which is needed in the exported CSV's USL. It's different for every time there's a different cookie.
Next, retrieves the CSV and parses it after removing a title line and extra characters.
Last, finds the correct column for the date we're looking for.
#703 
Well, at least I learned a lot from this mess...

Fixed DC to use time series CSV data

---

src/shared/lib/fetch/caching.js
src/shared/lib/fetch/get.js
src/shared/lib/fetch/index.js
src/shared/scrapers/AU/ACT/index.js

Fix AUS ACT, now their page turned into a powerBI dash. Ugh.
Grab it off their home page instead. Unfortunately this has no death count (currently 2).

Fix aus act again (plus some JSDOC improvements)

---

src/shared/scrapers/AU/QLD/index.js

QLD has a new table format, which is an improvement, hooray! Go QLD!
Now the table has much more data.
Would love to get around to fitting these geographic areas as well, but for now we're just doing state level.

fix AU QLD 2020-04-09

---

scripts/crawler.js
site/cross-check-report.js
src/events/crawler/get-sources/load-sources.js
src/events/crawler/scrape-data/normalize-locations.js
src/events/crawler/scrape-data/run-scraper.js
src/events/processor/find-features/index.js
src/qa/utils/qa-fetch.js
src/shared/lib/geography/country-levels.js
src/shared/lib/geography/index.js
tests/integration/scrapers/scrapers-all-test.js
tests/unit/shared/lib/datetime-test.js
tests/unit/shared/lib/fs-test.js
tests/unit/shared/lib/html-table-validation-test.js
tools/generate-crosscheck-html.js

This stuff was going nowhere, so lets delete it to stop being misleading.

remove extraneous args and imports

---

src/shared/scrapers/IN/index.js

India moved some columns around. In master we look for columns by their order, now we'll look by their heading content.
In place of https://github.com/covidatlas/coronadatascraper/pull/744/files which wouldn't be backwards compatible.

fix iso1:IN India state and country level scraper

---

src/shared/scrapers/US/VT/index.js

Long overdue VT scrapper

---

src/shared/scrapers/KR/index.js

Change to not care about order.
Use the iso codes for states.

fix iso1:KR South Korea state and country level scraper

---

src/shared/scrapers/AU/NSW/index.js
src/shared/scrapers/AU/index.js
src/shared/scrapers/ID/index.js
src/shared/scrapers/NZ/index.js
src/shared/scrapers/US/DC/index.js

fix maintainer to maintainers key in scraper objects

---

src/shared/scrapers/AU/ACT/index.js
src/shared/scrapers/PR/index.js
src/shared/utils/pivot-the-table.js

Seems like main issue was lack of `www.` for some reason isn't resolving. While I'm here I figured I'd get rid of the order-dependence.

fix iso1:PR Puerto Rico

---

src/shared/scrapers/US/CA/los-angeles-county.js

- Interestingly LA is replacing client-side using
a small JS file that looks for IDs.
- Grab the JS file, find the JSON, then use
that directly.

fix US CA Los Angeles

---

src/shared/scrapers/AU/SA/index.js

They're improving their markup, woohoo!

fix AU SA. Had bad structure of TH instead TBODY, now fixed so suit both

---

src/shared/scrapers/US/NH/index.js

Added counties to NH

---

src/shared/scrapers/IN/index.js

- I broke (Sorry!), then fixed it.
- Larry shorted it to get the release out.
- Now let's use it again since it works.

Use scraper for India

---

scripts/update-cache-ref.sh

Update cache ref, and script to automate that.

Cache apr 14

---

src/shared/lib/maintainers.js
src/shared/scrapers/US/CA/ventura-county.js

This fixes ventura county scraper from 3-30-20 through 4-14-20.

fix: ventura county scraper

---

src/shared/scrapers/AU/QLD/index.js
src/shared/scrapers/US/MD/index.js
src/shared/scrapers/US/SC/index.js

_Very_ small tweaks.  Ran regression against prior master reports, and everything is the same.
```
$ node tools/compare-report-dirs.js --left zzz0_master --right zzz1_SingleLine
data-2020-4-13.json
-------------------
equal
report.json
-----------
equal
ratings.json
------------
equal
features-2020-4-13.json
-----------------------
equal
crawler-report.csv
------------------
equal
data-2020-4-13.csv
------------------
equal
```

Tweak scraper code for migration.

---

src/shared/scrapers/TH/index.js

The old scraper didn't even make it a day without breaking so just removing it.

fix: add proper scraper for TH

---

src/shared/scrapers/NZ/index.js

I thought it was cumulative, it is instead currently in hospital.

fix: NZ their hospitalized means not cumulative

---

src/shared/scrapers/AU/QLD/index.js
src/shared/scrapers/AU/QLD/tests/43582a8490f66663656470136c825530.html
src/shared/scrapers/AU/QLD/tests/5667587d889302c59a05a19cfafa9947.html
src/shared/scrapers/AU/QLD/tests/expected.2020-04-16.json

Why bother caring what the cells are made of, we just need to find the last row and iterate through the direct descendants.

fix: AU QLD ever-changing HTML structure

---

src/shared/scrapers/JP/index.js
src/shared/scrapers/JP/tests/expected.2020-04-16.json

There is an ARCGIS for Japan, now we'll scrape it for case data at prefecture-level.
Would love any pointers from folks who have done a bit of ARCGIS before.

new scraper: JP including prefecture-level

---

src/shared/scrapers/PA/index.js

Thanks to @qgolsteyn and @camjc's idea, we can exploit the patient list we get to make a time series.
Note: also converted to fetching JSON because we've been getting stale CSV data.
Known issues / hacks:
- Does its own ArcGIS pagination in case we couldn't merge @qgolsteyn PR for official support of that.
- The two most recent data points in the timeseries are equal, which I think may be a timezone thing that will go away in li.

Convert PA to a timeseries

---

src/shared/scrapers/US/CA/santa-clara-county.js

Looks like we accidentally chucked the wrong month in the date. 🤷

actually deprecate US CA Santa Clara county

---

src/shared/scrapers/US/GA/index.js
src/shared/scrapers/US/GA/tests/5a236d71a0248fed6d9a42428936ac60.html
src/shared/scrapers/US/GA/tests/5b06dea46430d7c0276b93fbe05dc32a.html
src/shared/scrapers/US/GA/tests/expected.2020-04-17.json

They've added a `h` to their classname. Such fun. Lets match either.

fix US GA scraper

---

src/shared/scrapers/US/MI/index.js
src/shared/scrapers/US/MI/tests/15dc05f4643512e55238fa0e2e67a93b.html
src/shared/scrapers/US/MI/tests/expected.2020-04-17.json

caption changed, so reduced the words to make it match both cases.
While I was there I overhauled the heading matching so its not as brittle.
I still dislike how this is doing the monkey-patching around Detroit, hopefully someone can clean that up, and theres some weirdness about it throwing out certain rows that I don't understand.

fix US MI scraper, still seems slightly jank

---

src/shared/scrapers/US/NV/carson-city.js

Its moved and changed into a bunch of DIVs, sigh.

deprecate carson city NV USA

---

src/shared/scrapers/CA/NS/index.js

Stop it turning up in the scrape report.

properly deprecate CA NS

---

src/shared/scrapers/AU/QLD/index.js

Need to match something in the heading name now since there are other media releases in this list.

fix AU QLD (has other types of media release now)

---

package.json
src/shared/lib/fetch/cache-migration.js
yarn.lock

Fixes cache migration PT timezone casting / off-by-one-day errata

---

scripts/dist-errors.js
scripts/pre-launch.js

Launch check scripts.

---

src/shared/scrapers/ID/index.js
src/shared/scrapers/ID/tests/968a2cdd98a1f846c268a7debe59924c.html
src/shared/scrapers/ID/tests/expected.2020-04-25.json

#157  Summary
Indonesia added a couple of new fields. They're initialisms, so it was hard to figure out what they meant. Found the long-form inside one of their recent press releases, but translating that was still un-enlightening. So I'm adding notes about what we found and ignoring those fields until someone who understands indonesian can help us (is one of them 'tested'?).

ignore new fields in ID since we cant be sure what they map to

---

src/shared/scrapers/AU/NSW/index.js

Its a Sunday arvo and someones changing their html structure. Why not.

allow AU NSW labels to be th or td

---

src/shared/scrapers/AU/NSW/index.js

A bunch of spaces are now between the parts of the header. These AU scrapers will be the death of me.

AU NSW string parse before get key

---

src/shared/scrapers/US/VT/index.js
tools/generate-v1-cache.js

Fix vt cache key

---

src/shared/lib/fetch/index.js
src/shared/scrapers/US/TN/index.js
tools/generate-v1-cache.js

No change to regular prod code.

Fix cache keys

---

src/shared/scrapers/AU/NT/index.js
src/shared/scrapers/NZ/index.js
src/shared/scrapers/PR/index.js

fix AU/NT, NZ, PR

---

src/shared/scrapers/US/VA/index.js

`$ yarn start --location US/VA` works locally now, dist extract:
```
{
"state": "Virginia",
"country": "United States",
"aggregate": "county",
"sources": [
{
"url": "http://www.vdh.virginia.gov/",
"name": "VDH",
"description": "Virginia Department of Health"
}
],
"maintainers": [
{
"name": "Albert III",
"github": "aed3",
"url": "https://aed3.github.io",
"county": "iso1:US",
"flag": "🇺🇸"
}
],
"url": "https://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv",
"cases": 15846,
"deaths": 552,
"hospitalized": 2322,
"rating": 0.4117647058823529,
"coordinates": [
-79.4585,
38.0035
],
"tz": [
"America/New_York"
],
"featureId": "iso2:US-VA",
"population": 8535519,
"populationDensity": 81.83101405294138,
"countryId": "iso1:US",
"stateId": "iso2:US-VA", …
```

Fix US/VA: disable SSL.

---

scripts/status-slack-bot.js

Ref https://api.slack.com/reference/block-kit/blocks
Slack `text` blocks are limited to 3000 chars.  When we have many validation failures, we exceed that limit.  With this PR, the slack update now looks like this (only showing a subset of the errors)
This also prints the server response.

Stay within slack text limits.

---

src/shared/scrapers/CY/index.js

The Cyprus site (https://data.gov.cy/dataset/%CE%B7%CE%BC%CE%B5%CF%81%CE%AE%CF%83%CE%B9%CE%B1-%CF%83%CF%84%CE%B1%CF%84%CE%B9%CF%83%CF%84%CE%B9%CE%BA%CE%AC-%CE%B4%CE%B9%CE%B1%CF%83%CF%80%CE%BF%CF%81%CE%AC%CF%82-%CF%84%CE%B7%CF%82-%CE%BD%CF%8C%CF%83%CE%BF%CF%85-covid-19-%CF%83%CF%84%CE%B7%CE%BD-%CE%BA%CF%8D%CF%80%CF%81%CE%BF) has a CSV and download, but the CSV appears to be a day behind.
If you run `yarn start --location CY`, it returns:
```
- 0 cases
- 0 tested
- 0 recovered
- 0 deaths
- 0 active
```
but `yarn start --location CY -d 2020-04-30` returns
```
- 850 cases
- 58009 tested
- 96 recovered
- 15 deaths
- 739 active
```
and dist/data.json:
```
MacBook-Air:coronadatascraper jeff$ tail -n 30 dist/data-2020-04-30.json 
}
],
"sources": [
{
"description": "Official website for Cyprus …
```

Fix CY scraper.

---

src/shared/scrapers/US/SC/index.js

Same error as MO, IE, recently merged PRs.

Fix US/SC error due to source data using epoch as date.

---

src/shared/scrapers/AU/VIC/index.js
src/shared/scrapers/AU/VIC/tests/expected.2020-04-21.json

May as well scrape it when we can.

add tested scraper for AU VIC

---

src/shared/scrapers/US/OK/index.js

Bad key, should be called 'default' !

Fix US/OK cache key.

---

tools/generate-v1-cache.js

Migration check only, no code impact.

Fix cache migration check.

---

src/shared/scrapers/US/CA/colusa-county.js
src/shared/scrapers/US/CA/glenn-county.js

Fix us ca colusa glenn counties

---

src/shared/scrapers/US/MO/st-louis-county.js

Fix publishedDate format validation failure.

Fix MO/St Louis arcgis date parsing.

---

src/shared/scrapers/US/RI/index.js

Make match less strict, but still useful.

Fix US/RI heading match.

---

src/shared/scrapers/US/WV/index.js

Fix US/WV inconsistent URLs and formatting.

---

src/shared/scrapers/US/SC/index.js

Fix US/SC BOM marker.

---

src/shared/scrapers/US/NV/nye-county.js

Minor updates to https://github.com/covidatlas/coronadatascraper/pull/955.
Works, looks good!

Appastair us nv ny county

---

src/shared/scrapers/US/WV/index.js

Include US-WV cases at state level.

---

src/shared/scrapers/IN/index.js
src/shared/utils/assert-totals-are-reasonable.js

Closes https://github.com/covidatlas/coronadatascraper/issues/984

fix INdia by backporting from LI

---

src/shared/timeseries/index.js

Prior to this, the code was _only_ adding nulls.

Add growthFactor to timeseries.

---

tools/compare-report-dirs.js

Support multiple-file comparison.

---

src/views/constants.js
src/views/template.js

feat: add analytics

---

src/shared/lib/diffing/json-diff.js
tests/unit/shared/lib/diffing/json-diff-test.js
tools/compare-report-dirs.js

Updated tests for regression testing.

Fix comparison detail

---

src/shared/lib/errors.js
src/shared/scrapers/CA/NS/index.js
src/shared/scrapers/US/CA/orange-county.js
src/shared/scrapers/US/CA/san-benito-county.js

I believe this are incorrectly marked, given the comments.  They're not deprecated, they need to be updated.

Change incorrect DeprecatedError to NotImplementedError

---

src/shared/scrapers/US/PA/index.js

Further resolve https://github.com/covidatlas/coronadatascraper/issues/1014.

Move us/pa back one day.

---

src/shared/scrapers/US/CA/orange-county.js

OC was bad for a while, have tested this locally and looks OK for recent dates.

Fix Orange County.

---

src/shared/lib/fetch/index.js
src/shared/scrapers/US/TX/harris-county.js

Add Harris TX scraper specifically for icu and hospitalization data.

Harris county tx jz

---

src/shared/scrapers/US/AZ/index.js

ArcGIS data is actually timeseries.  We can use that instead of doing difficult Tableau scraping.

Switch US-AZ source to only use timeseries.

---

src/shared/scrapers/NL/index.js

If data is not available, old code returned empty array, which then caused
validation error 'iso1:NL: Error: Invalid data: scraper for iso1:NL returned 0 rows'.
Returning undefined follows our convention for 'empty' data, and doesn't
raise an error.
I'm not 100% sure this is the right thing to do, but it at least stops the error being thrown.

Fix NL when data not available.

---

covidatlas/graph.css
covidatlas/location-graph.js
src/http/get-000location/index.js

graph made with d3

---

covidatlas/base.css
covidatlas/index.css
covidatlas/lib/color.js

Replacement for https://github.com/covidatlas/coronadatascraper/pull/1046 (removed package.lock).

Typography and color updates.
