covidatlas/coronadatascraper

lib/fetch.js
`Needle` by default will wait indefinitely when fetching if the host does not send any data back, or the data takes very long to be retrieved.
An example url causing issue is from the South Dakota website (https://doh.sd.gov/news/Coronavirus.aspx#SD) which does not seem to send any data back currently.
This PR adds default timeouts for opening connections (5s), waiting for a response (5s), and downloading data (30s).
Feel free to let me know if these defaults should be tweaked.
=> Fix network timeout causing hangs

lib/fetch.js
Found a potential bug linked to timeseries data (when grabbing the CSV files from  Johns Hopkins repo for example)
Parser reports warning:
```
⚠️  Cannot go back in time to get https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv, no cache present
```
and throws a caught error:
```
TypeError: Cannot convert undefined or null to object
```
It appears we are not grabbing any timeseries data causing this line in `scrappers.js:31` to throw as it assumes that cases will not be empty:
```javascript
let latestDate = Object.keys(cases[0]).pop();
```
Traced the lack of data in cases to `fetch.js:52`:
```javascript
if (await fs.exists(filePath)) {
// stuff
else if (new Date(date) < new …
```
=> Fix cache issue causing undefined error

scrapers.js
This change updates the pull for the Santa Clara County website. The page code dynamically populates the DOM from an embedded JSON array. This made a simple HTML parsing not possible. Instead, we find the script tag containing the JSON array, use regex to parse it, and then feed back the counts as normal.
=> Update Santa Clara County

README.md, scrapers.js
This PR updates Ventura and Santa Cruz County. Santa Cruz county changed its formatting from H1 to H2 tag object. Ventura County had an issue with JS not populating the count text, however the counts are available in the the data-from or data-to attributes.
=> Update Ventura & Santa Cruz County

lib/transform.js
Congo-Kinshasa is the Democratic Republic of the Congo, which has three-letter code COD, while Congo is the different Republic of the Congo, which has three-letter code COG.
=> Map Congo (Kinshasa) to COD instead of COG

.gitmodules
This allows cloning with submodules without SSH. (`git submodule sync` will be needed to update the URL.)
Edit: This would conflict with updating the cache repository automatically using the submodule, but that seems best done with a separate SSH clone.
=> Use HTTPS for cache submodule

scrapers.js
This uses [the cases table](https://www.arcgis.com/home/item.html?id=b684319181f94875a6879bbc833ca3a6) for upper-tier local authorities with cases [reported to Public Health England](https://www.gov.uk/government/publications/covid-19-track-coronavirus-cases). Recoveries and deaths are not included and case counts are not summed since the sum is lower than the reported total case count:
> Total number for England may not match UTLA and NHS Regions number as some cases are awaiting geographical information.
Also no features since [the relevant dataset](https://data.gov.uk/dataset/6ee49b1e-0f4d-4079-90f4-b626e36d2035/lower-tier-local-authority-to-upper-tier-local-authority-april-2019-lookup-in-england-and-wales) doesn’t have geometry and refers to the Open Geography Portal instead.
=> Add scraper for United Kingdom

README.md, lib/transform.js, scrapers.js, tasks/scrapeData.js
Closes #82 
This PR adds rating calculation based on available fields, data type, encryption, whether we have to access it headless, and whether it has time series data. The maximum rating is 1.
In addition, it uses the calculated rating to break ties when deduping data that has identical priorities.
=> Calculate ratings for datasources based on objective criteria

scrapers.js
This adds Mono County using the headless scraper. Checked that data is correctly output to json file.
=> Added Mono County, CA

scrapers.js
This fixes three CA counties.
- Yolo County started adding ** which broke the regex
- Glenn County changed from FONT to SPAN tags
- San Joaquin started using a table
=> Fix Glenn, Yolo, and San Joaquin CA counties

scrapers.js
This fixes the Mono County to correctly pull the right cases. It was reporting 0 however the number of cases is also 0 so no change to the data. I added the number of tests given. This was not available previously and is how I recognized the issue.
=> Updated Mono County, CA to include tests

scrapers.js
Hey!
The README patch is just a minor proposal, feel free to say if you don't like that.
I have tried to test the scraper:
```
$ yarn start --location "DEU"
yarn run v1.22.4
$ NODE_OPTIONS='--insecure-http-parser' node cli.js --location DEU
(node:15641) ExperimentalWarning: The ESM module loader is experimental.
⏳ Scraping data for today...
🐢 Cache miss for https://covid19-germany.appspot.com/now at coronadatascraper-cache/2020-3-17/38f8f7262afb9fab969c26940d40bca8.json
🚦  Loading data for https://covid19-germany.appspot.com/now from server
(node:15641) Warning: Using insecure HTTP parsing
⚡️ Cache hit for https://opendata.arcgis.com/datasets/d14de7e28b0448ab82eb36d6f25b1ea1_0.csv from coronadatascraper-cache/2020-3-17/ea58672b23e340fbf8f209b7af40173c.csv
...
```
Seems to have worked in …
=> feat: add scraper for DEU (Germany)

scrapers/USA/CA/ventura-county.js
As of 3/18 the Ventura scraper was returning 0 cases. The page format changed that day. This patch parses the new page layout and returns the currently correct value of 13 cases.
=> Fixed Ventura, CA scraper to handle new html format

scrapers/USA/CA/ventura-county.js
Updated to the current best URL, keeping old scrapers working with the legacy url.
=> fix: update Ventura County, CA with current best url

src/events/crawler/tasks/fetchSources.js
This is needed to allow developers working on Windows to run the scraper locally. 
From https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows :
> Always use forward-slashes in glob expressions (patterns and [`ignore`](#ignore) option). 
> Use backslashes for escaping characters. With the [`cwd`](#cwd) option use a convenient format.
> 
> **Bad**
> 
> ```ts
> [
> 	'directory\\*',
> 	path.join(process.cwd(), '**')
> ]
> ```
> 
> **Good**
> 
> ```ts
> [
> 	'directory/*',
> 	path.join(process.cwd(), '**').replace(/\\/g, '/')
> ]
> ```
> 
I've tested this on Windows and Ubuntu.
=> fix: use forward slashes in glob patterns

site/map.js
Keeps label layer from the style/template map visible over the chloropleth layer.
=> Place cloropleth layer under label layer

.eslintrc.json, package.json
This PR turns off warnings for es-lint issues that we're currently disregarding. 
- consistent-return
- func-names
- jest/expect-expect
- jest/no-standalone-expect
- jest/no-try-expect
- no-async-promise-executor
- no-await-in-loop
- no-console
- no-continue
- no-labels
- no-param-reassign
- no-plusplus
- no-restricted-syntax
- no-shadow
- no-underscore-dangle
I don't have strong opinions about any of these rules - some are good practice, some seem a little arbitrary, and some we probably never intend to follow.
Either way, the current functioning of the site depends on code that breaks these rules. That code could be refactored, but without better test coverage it's not worth the risk of inadvertently breaking the site. 
I've also removed `git-add` from the `lint-staged` config, as per …
=> Quieter eslint

src/events/crawler/scrapers/CHE/index.js, src/events/crawler/tasks/findFeatures.js
Closes #305 
It adds a new field to detect the correct feature to use, via the `_featureId` field, which compares the content of that object to the properties of each feature we have in `coronavirus-data-sources`
=> feat: add CHE

src/events/crawler/scrapers/AUS/VIC/index.js
For Victoria, AUS, the 03-25 press release has the word `is` instead of `to` before the number of cases, which breaks the regex
=> fix: AUS Victoria

site/lib/color.js, site/map.js
- Updated `yellowOrangePurple` scale with slightly different colors
- Updated `yellowOrangePurple` scale to have exponential shift applied to colors 
- Removed lightness correction in `domainArray` since this should be done when creating a color scale to use within visualizatoins and not in the consumption of the color scale itself.
- Removed `adjustTanh` function from data (transformation should be done to color scale and not to data itself -- exponential shift on scale accomplishes this)
- Made `yellowOrangePurple` the default color scale as it provides a greater range of intensity levels for data to be visualized.
=> fix: update yellowOrangePurple scale, remove lightness correction

src/shared/scrapers/AUS/VIC/index.js
Victoria have a dashboard at https://app.powerbi.com/view?r=eyJrIjoiODBmMmE3NWQtZWNlNC00OWRkLTk1NjYtMjM2YTY1MjI2NzdjIiwidCI6ImMwZTA2MDFmLTBmYWMtNDQ5Yy05Yzg4LWExMDRjNGViOWYyOCJ9 that I can't scrape because its dynamic and the JSON is crazily structured and using some sort of auth.
They also have media releases that they keep changing the format of.
health.gov.au (AUS/index) has the same data anyway (sometimes slightly out of date), so I'm giving up on AUS/VIC until they can provide accessible data.
=> remove state-level scraper for VIC because their data is unusable, fall back to AUS

src/shared/scrapers/USA/CA/fresno-county.js
Currently the Fresno county scraper is concatenating Total cases and Travel related cases to report 3116 cases instead of 31. This fixes the issue.
=> Fix fresno county total cases

scripts/statusSlackBot.js, src/events/crawler/scrape-data/run-scraper.js, src/shared/lib/errors.js, src/shared/scrapers/AUS/VIC/index.js, src/shared/scrapers/USA/CA/sonoma-county.js
As mentioned in https://github.com/lazd/coronadatascraper/pull/453 from @chunder @lazd .
@lazd Wheres the bit we need to catch and ignore this?
Is this the approach we want (allow scrapers to come-good-again if they again match the original format) or do we want to split it out into dates and just immediately throw the error after the first bad date?
(and if this is the implementation we want, is DeprecatedError semantically correct? Maybe InconsistentFormatError or something? )
=> throw deprecated error for scrapers that cant give consistent format

src/shared/scrapers/AUS/ACT/index.js, src/shared/scrapers/AUS/NSW/index.js, src/shared/scrapers/AUS/NT/index.js, src/shared/scrapers/AUS/QLD/index.js, src/shared/scrapers/AUS/SA/index.js, src/shared/scrapers/AUS/VIC/index.js, src/shared/scrapers/AUS/WA/index.js, src/shared/scrapers/AUS/index.js
Was originally trying to harden some of the AUS scrapers, but then realised that ACT changed their whole website in the middle of a Sunday (why not) so wrote a new scraper for that too.
Now that everywhere has corona cases it might be worth doing a similar assertion globally; interested in your thoughts.
=> Harden AUS scrapers, add new scraper for completely changed ACT

site/index.html
This PR proposes adding [Sickly.app](https://sickly.app) to the homepage. Sickly uses CDS data to visualize the number of reported cases down to the county level.
=> Add sickly.app to homepage

src/shared/scrapers/AUS/ACT/index.js, src/shared/scrapers/AUS/NSW/index.js, src/shared/scrapers/AUS/NT/index.js, src/shared/scrapers/AUS/QLD/index.js, src/shared/scrapers/AUS/SA/index.js, src/shared/scrapers/AUS/VIC/index.js, src/shared/scrapers/AUS/WA/index.js, src/shared/scrapers/AUS/_shared/get-data-with-tested-negative-applied.js, src/shared/scrapers/AUS/_shared/get-key.js
Trying out some patterns for how best to lookup. Wondering if there can be a shared lookup across scrapers (like if the word deaths is included, then its very probable to be the deaths item).
AUS ACT has a death now, so they've added 'lives lost'.
=> fix AUS ACT (deaths) and consolidate key lookup

src/shared/scrapers/USA/NJ/index.js
also fixed a column name change for total cases
=> update: NJ now reporting county deaths

src/shared/scrapers/USA/MN/index.js, src/shared/scrapers/USA/NH/index.js
New Hampshire's source stopped reporting county-level data and I'm unable to find any government source that's showing it.
MN was checking for a non-existent attribute `item.attributes.CV_Updated`, this check was removed.
=> deprecate NH + fix errors in MN

src/shared/scrapers/USA/MI/index.js, src/shared/scrapers/USA/UT/index.js
Fixes `Not Reported County` in Michigan as well as `Tri County Health District` and `Bear River Health District` in Utah.
Closes https://github.com/covidatlas/coronadatascraper/issues/363.
=> Fix Issue 363: Changes to UT & MI, USA

src/shared/lib/schemas/ratings.json
Just noticed that ESP was showing up as not a timeseries, then noticed that **all** sources where showing up as not a time series, whether they are or not. 
Tracked it down to the ratings schema, which was missing the `timeseries` property.
=> Add `timeseries` to ratings schema

src/shared/scrapers/ESP/index.js
On the ESP scraper definition:
- I'd left out the `type` property, which is csv
- I'd misunderstood the `sources` property; I've renamed that to `_endpoints` (for internal use by the scraper) and populated the original sources correctly (Spain Min. of Health & Dept. of National Security).
=> ESP metadata: add type, fix sources

package.json, src/shared/cli/cli-args.js, src/shared/timeseries/index.js, src/shared/timeseries/runCrawler.js, src/shared/timeseries/worker.js
`yarn timeseries` has been running out of memory on many occasions. To prevent this from occurring, we can run the crawler in its own process. This PR adds a new function `runCrawler` which is called from `timeseries/index.js` and takes care of creating a child process and retrieving data from this process when crawling is done.
=> feat: move running crawler for timeseries to its own process

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/data_issue.md, .github/ISSUE_TEMPLATE/new-scraper.md, .github/ISSUE_TEMPLATE/report-bug.md, .github/ISSUE_TEMPLATE/request-feature.md, .github/ISSUE_TEMPLATE/tech-debt.md, .github/PULL_REQUEST_TEMPLATE.md
Some templates created after discussions today with @ryanblock and @lazd.  These files in .github pre-populate new issues and pull requests.  They are mostly regular yaml files, with some extra markup for issues at the top.
There are multiple issue templates, which I put together looking at the existing issues, and some other templates.  When you create a new issue, you're shown the below to pick the template you'll use:
The issues will have labels auto-assigned.
We can only have one PR template.  It has some comments at the top to remind people to do some things (run tests, lint, etc), and then has some standard questions.
When these files are present in the default branch (`master`), they'll become active.
=> Add PR template, and multiple issue templates.

src/shared/scrapers/AUS/SA/index.js
South Australia added a table row, which throws an Error that we noticed in the scraper report. Now we have a recovered count, just a tested count still to go if they ever add it.
This is a backwards compatible change.
=> add Recovered for AUS-SA

src/shared/scrapers/AUS/VIC/index.js
We have a thousand cases now, so /d wasn't matching `1,000`, it thought it was `1`. Oh no!
=> [patch] fix AUS VIC thousands separator

src/shared/lib/maintainers.js, src/shared/scrapers/USA/MO/index.js, src/shared/scrapers/USA/MO/st-louis-county.js
Fixes issue #599 
St. Louis County is posting most recent changes in cases on county page: https://stlouisco.com/Your-Government/County-Executive/COVID-19
Numbers from MO Health Dept have a delay.
*  Scrape case numbers for St. Louis County directly from linked ArcGIS map from county website.
*  No longer combining St. Louis County cases with St. Louis City
Please note, before this change we were merging case numbers of St. Louis City with St. Louis County.  I'm not sure what the reasoning was originally, but as a user of the source code I would personally prefer to keep them separate since we seem to separate city/county for other areas, such as my home town Richmond City vs Richmond County.
=> Scraper 599

src/shared/scrapers/USA/MO/index.js
Fixes error: TypeError: datetime.scrapeDateIsAfter is not a function
=> Fix MO datetime import.

src/shared/scrapers/JHU.js
Note the 'US' conditional branch is never hit there because of
the lack of US states in the global data (separate issue).
Closes #618
=> Fix scraping of JHU 'recovered' data

src/shared/scrapers/AUS/aus-from-wa-health/index.js
WA Health has Death counts for the whole country by state, even though the federal government doesn't in an accessible format. It seems slightly delayed compared to the federal government case count.
=> add scraper for AUS states via WA health

src/shared/scrapers/AUS/NSW/index.js
Looks like NSW is following a pretty consistent format for deaths, so lets add that data where we can.
=> scrape NSW AU deaths from paragraphs where possible

src/shared/scrapers/IND/index.js
#654 - The previous version of the scraper was not using the right table name to access the data. Just change the table name.
The previous version of the scraper was not using the right table name to access the data. Just change the table name.
//    const $table = $('#cases table');
const $table = $('#state-data');
changed the name of the table reference from "cases table" to "state-data"
Does not impact the coverage.
This should not break again so long as the table name is not changed.
=> fixed the table-name in IND scraper

src/events/processor/find-features/index.js, src/shared/utils/timeouts.js
This changes the caching strategy of the geo-tz library so that data is stored in-memory rather than using the timed-cache library which will result in no timeouts being applied to the data. Also, a comment has been rewritten to not call out the geo-tz library specifically.
=> Change the caching strategy of geo-tz library

tests/unit/shared/scrapers/scrapers-all-test.js
Addresses #604 
Adds tests for all scraper files (all `*.js` files in `src/shared/scrapers`, excluding files or folders that start with underscore.  Provides the collection of scraper objects so that additional tests for all scrapers can be added, if needed.
Sample test spec output:
```
srapers-all-test: all scraper schema
/JHU.js schema ok
/AUS/index.js schema ok
/BRA/index.js schema ok
/CAN/index.js schema ok
... etc.
```
These tests run with the unit tests, `yarn test`.  It appears to take a moment to load all of the files, but still super fast.
=> Unit tests: Verify scraper schema

src/shared/cli/cli-args.js, src/shared/index.js, src/shared/lib/fetch/get.js, src/shared/lib/fetch/index.js
(Code salvaged from Herb C's PR #580.)
Adds `--onlyUseCache`, to ensure that we stick with cache!
This change opens up the possibility for testing things entirely offline.  If a cache misses, it returns null, and then scrapers have to deal with that.
```
$ yarn start --location "PA, USA" --onlyUseCache -d 2020-04-04
yarn run v1.22.4
$ node src/shared/cli/index.js --location 'PA, USA' --onlyUseCache -d 2020-04-04
⏳ Fetching scrapers...
✅ Fetched 135 scrapers!
✅ All scrapers are valid!
🐢  Cache miss for https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx at coronadatascraper-cache/2020-4-4/6847ef86804ff0c3c03f31ca00d7eb6d.html
❌ Error processing PA, USA:  TypeError: $ is not a function
at Object.scraper (/Users/jeff/Documents/Projects/coronadatascraper/src/shared/scrapers/U …
```
=> Add onlyUseCache command-line flag

src/shared/scrapers/AU/NSW/index.js
They have 'confirmed cases' in their deaths row as a parenthetical, so the unknown row assertion didn't trigger, haha.
Keep the paragraph scraper as a fallback for backwards compatibility.
=> [patch] support deaths in table now, backwards compatible

src/shared/scrapers/ID/index.js
Add scraper for Indonesia. Google translate to figure out whats cases, deaths, recovered.
=> scrape Indonesia iso1:ID

docs/getting_started.md, docs/sources.md, src/events/crawler/get-sources/load-sources.js, src/events/crawler/get-sources/validate-sources.js, src/events/crawler/scrape-data/run-scraper.js, src/shared/cli/cli-args.js, src/shared/index.js, src/shared/timeseries/run-crawler.js
Updates the `--skip` and `--location` filters to instead use relative file paths only.  We're moving to iso codes, so the filters are changing, and it's hard to guess what the right thing is.
Addresses issue #706 (yarn flags), and docs.
```
$ yarn start --location "US/NV"
yarn run v1.22.4
$ node src/shared/cli/index.js --location US/NV
⏳ Fetching scrapers...
✅ Fetched 138 scrapers, filtered to 3.
... etc
$ yarn start --location "US/NV/carson-city.js"
yarn run v1.22.4
$ node src/shared/cli/index.js --location US/NV/carson-city.js
⏳ Fetching scrapers...
✅ Fetched 138 scrapers, filtered to 1.
... etc
```
`start` quits if nothing matches:
```
$ yarn start --location "xxx"
yarn run v1.22.4
$ node src/shared/cli/index.js --location xxx
⏳ Fetching scrapers...
location filter returned 0 scrapers. …
```
=> Fix command line scraper filters

docs/getting_started.md, package.json
`yarn options` : A nice-to-have only, b/c I always forget what the options are.
```
$ yarn options
yarn run v1.22.4
$ node -r esm src/shared/cli/cli-args.js -h
Options:
--version           Show version number                              [boolean]
--date, -d          Generate data for or start the timeseries at the provided
date in YYYY-M-D format                           [string]
--endDate, -e       The date after which to stop generating timeseries data
[string]
--location, -l      Scrape only the location provided by full name, i.e City,
County, State, Country                            [string]
--country, -c       Scrape only the country provided, like AUS        [string]
--id, -i            Scrape only the location provided by id           [string]
--skip, -s          Skip the …
```
=> Add 'yarn options' to list cli options.

src/shared/lib/fetch/get.js, src/shared/lib/fetch/index.js, src/shared/scrapers/RU/index.js
Fixes issue #483 , "RUS scraper breaks caching".
RUS would use needle directly to get a CSRF token, bypassing caching.  Here are logs for two runs, you won't see any cache hits:
On master, run 1:
```
https://yandex.ru/maps/api/covid?csrfToken=140572faa6dabfb4e04ff2875d59f177ffe5381d:1586392377
🐢  Cache miss for https://yandex.ru/maps/api/covid?csrfToken=140572faa6dabfb4e04ff2875d59f177ffe5381d:1586392377 at coronadatascraper-cache/2020-4-8/eaf37e9f477e1e71cd489f7860445725.json
🚦  Loading data for https://yandex.ru/maps/api/covid?csrfToken=140572faa6dabfb4e04ff2875d59f177ffe5381d:1586392377 from server
✏️  coronadatascraper-cache/2020-4-8/eaf37e9f477e1e71cd489f7860445725.json written
```
On master, run 2
```
https://yandex.ru/maps/api/covid?csrfToken=632672b8fee965318ae931435fcaa1f118d1cde0 …
```
=> Fix issue 483: rus scraper breaks caching

src/shared/lib/datetime/iso/now.js, tests/unit/shared/lib/datetime-test.js
Fix for #637 
Before the change, datetime.now.utc() didn't have Z.
After the change, it does.
@hyperknot - is this all there is to it?  I ran `yarn start` and didn't see any obvious explosions.
=> Fix issue 637: add Z to datetime.now.utc()

package.json, src/shared/scrapers/GB/ENG/gss-codes.json, src/shared/scrapers/GB/ENG/index.js, src/shared/scrapers/GB/_shared.js, src/shared/scrapers/GB/gss-codes.json, yarn.lock
GB / England using ISO codes
GB / EN was using names, population wasn't found.
Population is found.
Lots of changes in country-levels, this part is quite simple. It's using an internal code system "GSS" which perfectly maps to counties. Added `gss-codes.json`
=> GB / England using ISO codes

src/shared/scrapers/AU/QLD/index.js, src/shared/scrapers/AU/_shared/are-numbers-close.js, src/shared/scrapers/AU/aus-from-wa-health/index.js, src/shared/scrapers/AU/index.js
QLD changed their header to be a proper thead.
WA states total doesn't add up, like the federal one sometimes doesn't.
=> fix AUS scrapers (QLD, AUS from WA health)

src/shared/scrapers/AU/QLD/index.js
QLD has changed their label. Add a label fragment to match both the old and the new labels for `cases`.
=> add alternate label for cases AU QLD

src/shared/scrapers/UA/index.js
Modified Ukraine to use `state`  rather than `county` level. This was a copy-paste mistake that wasn't caught.
Changed `county: clIdMap` to `state: clIdMap`
=> fixed iso1:UA incorrect usage of county

tests/integration/scrapers/scrapers-all-test.js
=> Must catch failed promise, or all yarn tests blow up.

src/events/crawler/scrape-data/run-scraper.js, src/events/processor/find-features/index.js, src/shared/lib/geography/country-levels.js
Reproduce the problem with `yarn start -l US/UT`. It will crash.
Some counties in usa-counties.js are of type `Polygon`; simply wrapping their coordinates in an array makes them into `MultiPolygons`, and then this concatenation will work.
=> Convert Polygons to MultiPolygons for concatenating counties

src/shared/scrapers/IN/index.js
This scraper sometimes fails, I think they can't handle the traffic volume. Lets add an assertion early on in the pipe so we know if its the scraping logic or just the whole page that is (generally temporarily) broken.
=> add additional assertion to ID, their site seems flaky

docs/sources.md, src/events/crawler/get-sources/load-sources.js, src/events/processor/write-data/index.js, src/shared/cli/cli-args.js, src/shared/lib/diffing/json-diff.js, src/shared/lib/diffing/string-diff.js, tests/unit/shared/lib/diffing/json-diff-test.js, tests/unit/shared/lib/diffing/string-diff-test.js, tools/compare-report-dirs.js
This adds a simple diffing script for generated CSV and JSON reports,
with human-friendly output.  This lets devs refactor and verify code
more safely.
The script usage is detailed in the docs.  In summary, here's how it's used:
Before starting work (or git checkout a SHA you want to use as
reference), generate baseline reports:
```
yarn start --date 2020-04-06 --onlyUseCache --location US/NV --writeTo zz_before
```
After doing your work, regenerate to a different folder using the same
cached data:
```
yarn start --date 2020-04-06 --onlyUseCache --location US/NV --writeTo zz_after
```
Use new script `tools/compare-report-dirs.js`, comparing the "left"
and "right" folders.  Each report is listed with the differences:
```
$ node tools/compare-report-dirs.js --left zz_before --right zz_after …
```
=> Add tool compare reports

src/shared/scrapers/IN/index.js
`Nagaland` is now being used. Seems like these are almost always (see comment) aligned to our names for them, so lets just add them all in at once and pick up any weird ones as they come up.
=> add remaining regions to IN

src/shared/scrapers/TH/index.js
Apparently the first 'confirmed case' means 'Confirmed patients (people)' second 'confirmed case' means 'Patient confirms the group travels from abroad and is quarantined in a designated area of the state (person)' 🤷
=> Add scraper for Thailand

package.json, src/shared/scrapers/AT/index.js, src/shared/scrapers/BR/index.js, src/shared/scrapers/CY/index.js, src/shared/scrapers/LT/index.js, src/shared/scrapers/LV/index.js, src/shared/scrapers/NL/index.js, src/shared/scrapers/SA/index.js, src/shared/scrapers/SE/index.js, src/shared/scrapers/SI/index.js, src/shared/scrapers/US/DC/index.js, src/shared/scrapers/US/GA/index.js, src/shared/scrapers/US/KS/index.js, src/shared/scrapers/US/MD/index.js, src/shared/scrapers/US/SC/index.js, src/shared/scrapers/US/TN/index.js, src/shared/scrapers/US/VT/index.js, src/shared/scrapers/ZA/index.js, tests/unit/shared/scrapers/scrapers-all-test.js
This changes the layout of code in scrapers so that all of them are on a single line.  This will let me quickly change over all scrapers using a simple regex to a new API for fetch and get, which will _greatly_ help with cache migration.
In summary, any call to `fetch.XXXX(` must all be on one line, no breaks, no nesting of fetch and other code.  I've added a unit test to run on all scraper code that uses fetch.
I ran the reports on the latest master, and on this branch (rebased off of the same), and the reports were identical:
```
$ yarn start --onlyUseCache -d 2020-4-13 --writeTo zzz0_master
$ yarn start --onlyUseCache -d 2020-4-13 --writeTo zzz1_SingleLine
$ node tools/compare-report-dirs.js --left zzz0_master --right zzz1_SingleLine
data-2020-4-13.json: equal
report.json: equal …
```
=> Change all scrapers fetch on single line

src/shared/scrapers/IN/index.js
Strip out any `#`s before mapping the state name to ID
=> fix: IN hash in state name

src/shared/scrapers/US/CA/alameda-county.js, src/shared/scrapers/US/CA/calaveras-county.js, src/shared/scrapers/US/CA/del-norte-county.js, src/shared/scrapers/US/CA/glenn-county.js, src/shared/scrapers/US/CA/kern-county.js, src/shared/scrapers/US/CA/madera-county.js, src/shared/scrapers/US/CA/marin-county.js, src/shared/scrapers/US/CA/mendocino-county.js, src/shared/scrapers/US/CA/merced-county.js, src/shared/scrapers/US/CA/orange-county.js, src/shared/scrapers/US/CA/riverside-county.js, src/shared/scrapers/US/CA/sacramento-county.js, src/shared/scrapers/US/CA/san-benito-county.js, src/shared/scrapers/US/CA/san-bernardino-county.js, src/shared/scrapers/US/CA/santa-barbara-county.js, src/shared/scrapers/US/CA/santa-clara-county.js, src/shared/scrapers/US/CA/santa-cruz-county.js, src/shared/scrapers/US/CA/solano-county.js, src/shared/scrapers/US/CA/yolo-county.js
This PR deprecates currently failing US/CA county scrapers. I am proposing this change as I do not see us having the capacity to maintain these scrapers and we already have aggregate sources covering the state of California. I am still allowing the scraper to cache their URL in case we are able to revisit these sources at a later date.
=> fix: deprecate failing US/CA county scrapers

package.json, yarn.lock
New major version using a much better GeoJSON simplification. 
features.json down from 50 MB to 15 MB!
By converting it to TopoJSON later on, we can make it to 5 MB, which is only 1.7 MB gzipped (all countries, states and counties together!)
timeseries.csv is the same as in master, except for some lower digit differences in center coordinates.
map is visually the same as in master.
=> Update country-levels to v2.0.0

src/shared/scrapers/AU/VIC/index.js, src/shared/scrapers/AU/VIC/tests/expected.2020-04-21.json
Seems like its standardised a bit now, so this mostly works. We have a good cache of these so we may as well extract what we can.
=> scrape more of AU VIC data from paragraphs

tools/generate-v1-cache.js
Tested out, sample call:
` node tools/generate-v1-cache.js node --dest zz-migration  --location US/WA`
Works fine ... _I think_.
=> Add location filter for cache migration.

src/shared/scrapers/US/covidtracking.js
For US states, COVIDTracking provides a higher quality source than anything else. We should use it for state level over anything else.
This fixes the issue with NY #823 as well as possibly many other issues with states.
=> Use COVIDTracking for US states

src/shared/lib/fetch/cache-migration.js, src/shared/scrapers/US/VA/index.js
Fix cache migration, VA was creating bad cache key names.
Prior:
`2020-03-23t04_00_00.000z-Virginia Beach-888b1.pdf`
Fixed to:
`2020-03-23t04_00_00.000z-virginiabeach-888b1.pdf`
Can regen the cache for this with:
`node tools/generate-v1-cache.js --location US/VA/index.js -d zz-regen-us-va`
=> Fix VA cache keys.

src/events/processor/write-data/dump-regression-raw.js, src/shared/cli/cli-args.js, src/shared/index.js
This dumps raw scraped data to a new report, `raw.json`, stored in dist.
Sample output: 
```
[
{
"_path": "/Users/jeff/Documents/Projects/coronadatascraper/src/shared/scrapers/US/CA/san-diego-county.js",
"county": "fips:06073",
"state": "iso2:US-CA",
"country": "iso1:US",
"timeseries": false,
"certValidation": true,
"priority": 0,
"cases": 2943,
"deaths": 111
}
]
```
The new routine only includes out a handfull of fields from the raw scraper data in the report, and the resulting file is ~ 3 mb.
With this output, we can work on getting regression testing in place for corresponding sources in li.
* added `--dumpRaw` to options, eg `yarn start --dumpRaw`.  The raw report isn't written if that's not set.
=> Add dumpRaw for regression testing with li.

src/shared/scrapers/US/GA/index.js
GA changed their site to use React, and no longer have the "cloudfront" in the first index page.
The caching code would have failed entirely yesterday, so I don't think we have any cache for it.
Running locally, everything looks good:
```
$ yarn start --location US/GA; echo '----------------------'; tail -n 30 dist/data.json
...
----------------------
"state": "Georgia",
"country": "United States",
"url": "https://dph.georgia.gov/covid-19-daily-status-report",
"aggregate": "county",
"sources": [
{
"url": "https://dph.georgia.gov",
"name": "Georgia Department of Public Health"
}
],
"cases": 23928,
"deaths": 1023,
"hospitalized": 4898,
"rating": 0.39215686274509803,
"coordinates": [
-83.2225,
32.6795
],
"tz": [
"America/New_York"
],
"featureId": "iso2:US-GA",
"population": 10617423, …
```
=> Fixed current GA scraper.

src/shared/scrapers/BR/index.js
Fixes, seems like it works.
Haven't tried to generalize any libs or anything, just getting the current thing to work.
lint and unit tests pass, runs locally and looks good:
`$ yarn start --location BR`: 
```
✅ Data scraped!
- 0 cities
- 27 states
- 0 counties
- 1 countries
ℹ️  Total counts (tracked cases, may contain duplicates):
- 143772 cases
- 0 tested
- 0 recovered
- 10034 deaths
- 0 active
```
```
data:
{
"country": "Brazil",
"sources": [
{
"description": "Secretaria de Vigilância em Saúde do Ministério da Saúde",
"name": "SVS-MS",
"url": "https://covid.saude.gov.br/"
}
],
"url": "https://covid.saude.gov.br/",
"maintainers": [
{
"name": "Felipe Roberto",
"email": "contato@feliperoberto.com.br",
"url": "http://feliperoberto.com.br",
"github": "feliperoberto",
"country": "iso1:BR", …
```
=> Fix broken BR scraper.

src/shared/scrapers/US/RI/index.js
Fix broken scraper.
The code has a small amount of duplication that could be refactored, but it's more important to get it in, so we can get data.
I ran it locally, and from what I can tell, it's working.
extract of dist.json, matches numbers at https://ri-department-of-health-covid-19-data-rihealth.hub.arcgis.com/:
```
[
{
"state": "Rhode Island",
"country": "United States",
"sources": [
{
"url": "https://health.ri.gov/data/covid-19/",
"name": "State of Rhode Island Department of Health"
}
],
"url": "https://health.ri.gov/data/covid-19/",
"tested": 60165,
"cases": 8247,
"deaths": 251,
"hospitalized": 269,
"discharged": 55,
"aggregate": "county",
"rating": 0.45098039215686275,
"coordinates": [
-71.5075,
41.584
],
"tz": [
"America/New_York"
],
"featureId": "iso2:US-RI",
"population": …
```
=> Fix US/RI scraper.

src/shared/scrapers/US/CO/index.js
Resolves https://github.com/covidatlas/coronadatascraper/issues/928
`yarn start --location US/CO` works for today.  data.json extract:
```
{
"state": "Colorado",
"country": "United States",
"aggregate": "county",
"url": "https://opendata.arcgis.com/datasets/7dd9bfa5607f4c70b2a7c9634ccdca53_0.csv",
"cases": 15284,
"deaths": 777,
"hospitalized": 2697,
"tested": 72390,
"rating": 0.49019607843137253,
"coordinates": [
-105.551,
38.9975
],
"tz": [
"America/Denver"
],
"featureId": "iso2:US-CO",
"population": 5758736,
"populationDensity": 21.330560753945722,
"countryId": "iso1:US",
"stateId": "iso2:US-CO",
"name": "Colorado, United States",
"level": "state"
}
```
```
"cases": 15284,
"deaths": 777,
```
Match the county numbers rolled up, and hosp/tested/pop at the state level are read from the …
=> Fix US/CO.

src/shared/scrapers/US/MO/index.js
MO switched to epoch for edit date in their data sources:
`$ cat coronadatascraper-cache/2020-4-27/9cd650122f1e65a5a95a77187448db0c.csv` =
`116,Kansas City, ... 2020-04-27T18:13:20.273Z,mophep,,,,,,,,,,,`
For the next date (2020-4-28) the same url:
`116,Kansas City, ... 1588100245140,mophep,,,,,,,,,,,`
`1588100245140` is epoch.  This is giving us a ton of validation errors:
```
$ yarn start --location US/MO/index.js -d 2020-04-28
...
Kansas City, Missouri, United States .publishedDate should match format "date-time"
...
```
With this fix, all is well.
Closes https://github.com/covidatlas/coronadatascraper/issues/936
=> Fix US/MO validation errors due to data using epoch for dates.

package.json, src/shared/scrapers/JP/index.js, src/shared/utils/get-iso2-from-name.js, yarn.lock
Back-port get-iso2-from-name and replace the prototype from JP with the fully defined function.
Aim is to make back/forward porting easier between the two repos.
=> back-port get-iso2-from-name

src/shared/scrapers/AU/WA/index.js, src/shared/scrapers/AU/WA/tests/expected.2020-05-02.json
They added a header, and its pretty obvious I messed up the mapping of the old one (should be testedNegative, not tested), so fix both.
=> fix AUS WA with new heading for tested

src/shared/scrapers/TW/index.js
Minor updates to https://github.com/covidatlas/coronadatascraper/pull/958.
Sample returned data, running today:
```
{
date: '2020-05-07',
country: 'iso1:TW',
cases: 440,
recovered: 347,
deaths: 6,
tested: 66046,
negative: 64754
}
```
Looks good!
=> Add tw source

src/shared/timeseries/index.js, tools/compare-report-dirs.js
This is useful for regression.
Example usage: `yarn timeseries -d 2020-5-6 -e 2020-5-6 --writeTo zzTIMESERIES`
If --writeTo isn't specified, it writes to dist.
This also fixes the report comparison tool, minor tweaks, for timeseries regression, eg
`node tools/compare-report-dirs.js --left dist --right zzTIMESERIES/`
=> Add timeseries writeTo support, fix comparison

src/shared/scrapers/TW/index.js
Hi Guys,
So we're using this as a datasource for our serverless API ([CoronaAPI/coronaAWS](https://github.com/coronaapi/coronaaws)).
When executing the scraper and importing the resulting data into DynamoDB however, the import fails due to the empty string in this specific crawler.
Hope this is alright!
=> Update TW URL description

src/shared/scrapers/CA/NS/index.js
Was throwing "not implemented".  Using a new timeseries for NS.
Yarn start now gives
```
┌───────────┬────────┐
│  (index)  │ Values │
├───────────┼────────┤
│   cases   │  1037  │
│  tested   │ 35703  │
│ recovered │  930   │
│  deaths   │   55   │
└───────────┴────────┘
```
=> Fix CA/NS.

site/lib/color.js, site/map.js
This should add an option to show the death rate per population in addition to the confirmed infected cases, as shown here:
=> Show deaths rate in addition to confirmed cases rate

src/shared/lib/maintainers.js, src/shared/scrapers/US/CA/san-francisco-county.js
Completes the work of @1ec5, branch datasf-1011.
The numbers match https://data.sfgov.org/stories/s/fjki-2fab.
vs this PR:
```
$ yarn start --location US/CA/san-francisco-county.js
...
Total counts (tracked cases, may contain duplicates):
- 2325 cases
- 50554 tested
- 0 recovered
- 40 deaths
- 0 active
```
I didn't include hospitalizations, as I didn't really trust the data.
=> Datasf 1011 handle timeseries

covidatlas/location-graph.js, package.json, scripts/download-li-s3-reports-to-dist.sh, site/index.html, src/http/get-000location/index.js, src/http/get-api-features-000location/index.js, src/http/get-api-locations-000location/index.js, src/http/get-api-timeseries-000location/index.js, src/http/get-data/index.js, src/macros/build.js, src/views/constants.js, src/views/lib/features.js, src/views/lib/geography.js, src/views/lib/timeseries.js
Use Li reports from S3 instead of CDS data.
I was able to test the covidatlas.com changes locally (with yarn devcovidatlas), but couldn't check CDS as I don't know how to build/deploy the front end locally.
* `yarn start` is disabled; `yarn timeseries` pulls down Li reports from s3 to dist
* `yarn start-old` and `yarn timeseries-old` run the old scripts in case you're feeling nostalgic
* `src/macros/build.js` changed to create data using new Li data structures
* dummy reports created for ratings.json and report.json
* covidatlas pages fixed (or sections disabled to expedite launch) -- see `//TODO` comments in code
* changed covidatlas.com/data links to pull from s3
* changed links on coronadatascraper.com
=> Replace cds dist reports with li s3 reports
